### ISSUE TITLE
Some rows don't delete after check-in

### ISSUE THREAD

**Issue by dwertheimer** [DavidWittman/serverless-southwest-check-in#12]
Had three people on the same flight (separate reservations). All seemed to get checked in appropriately, but one of them did not get removed from the DB after check-in. 

Checked Dynamo, and indeed 2/3 are gone. 1 of 3 remains in the db. 

```
17:35:58
[INFO]	2017-02-22T17:35:58.50Z	5c334a4b-f925-11e6-9c26-31f3539740eb	Removing completed check-in from DynamoDB
[INFO]	2017-02-22T17:35:58.50Z	5c334a4b-f925-11e6-9c26-31f3539740eb	Removing completed check-in from DynamoDB

17:35:58
[ERROR]	2017-02-22T17:35:58.75Z	5c334a4b-f925-11e6-9c26-31f3539740eb	Error deleting item from DynamoDB: 'HTTPStatusCode'
[ERROR]	2017-02-22T17:35:58.75Z	5c334a4b-f925-11e6-9c26-31f3539740eb	Error deleting item from DynamoDB: 'HTTPStatusCode'
```

**Comment by DavidWittman** [comment]
Hmm... I wonder if you hit a write capacity restriction since the writes per second are defaulted to 1 (in serverless.yml) and you had multiple check-ins occurring around the same time.

> If your application's read or write requests exceed the provisioned throughput for a table, DynamoDB might throttle that request. When this happens, the request fails with an HTTP 400 code (Bad Request), accompanied by a ProvisionedThroughputExceededException. The AWS SDKs have built-in support for retrying throttled requests. However, you might want to consider using exponential backoff logic in your error handling code. For more information, see Error Retries and Exponential Backoff.

Was there anything else in the traceback? Feel free to email it to me if there's anything sensitive in there.

**Comment by DavidWittman** [comment]
@dwertheimer This _may_ have been fixed by #15. You should be able to `serverless deploy` (after `git pull`ing) to update the configuration of your DynamoDB database. I'll know more with a full traceback from the failure, but there's some chance I'm logging that incorrectly based on the output you provided.

**Comment by dwertheimer** [comment]
This may have been part of the issue, so can't hurt to raise this a bit like you did.

The error I was seeing had nothing to do with the delete itself. It was caused by a dict key error, even when the call succeeded, because the code said:
`  if resp['HTTPStatusCode'] != 200:`
but I think that should have read:
`  if resp['ResponseMetadata']['HTTPStatusCode'] != 200:`
because `resp` is a two-dimensional array:
`{ 'ResponseMetadata':  { 'HTTPHeaders': { 'content-length': '2',
'content-type': 'application/x-amz-json-1.0',
'date': 'Thu, 23 Feb 2017 06:02:54 GMT',
'x-amz-crc32': '2745614147',
'x-amzn-requestid': 'QB8JA743V4CC5CD2JOGFQ5OS7JVV4KQNSO5AEMVJF66Q9ASUAAJG'},
'HTTPStatusCode': 200,
'RequestId': 'QB8JA743V4CC5CD2JOGFQ5OS7JVV4KQNSO5AEMVJF66Q9ASUAAJG',
'RetryAttempts': 0}}`

I was getting "Key Error" on the deletes even after changing the rate limits. But when I run it that way (`  if resp['ResponseMetadata']['HTTPStatusCode'] != 200:`) it works fine, no errors, so that will clean things up a bit if you make that change.

**Comment by DavidWittman** [comment]
Thanks @dwertheimer... That seems to be it. I'm fixing that now, and hopefully when I add in some more robust testing with [moto](https://github.com/spulec/moto) I'll catch these things sooner.
