### ISSUE TITLE
Error: Error asking for user input: Cannot parse value for variable domains

### ISSUE THREAD

**Issue by Fffrank** [DavidWittman/serverless-southwest-check-in#44]
Having trouble entering domain name in the make deploy....

```
terraform apply terraform/
var.admin_email
  This email address will be used for alerts and BCCs on confirmations

  Enter a value: xxxxxxx@gmail.com

var.domains
  List of domains/subdomains to create the service under. WARNING: The MX records for this domain will be overwritten!

  Enter a value: xxx.pw


Error: Error asking for user input: Cannot parse value for variable domains ("xxx.pw") as valid HCL: At 1:39: Unknown token: 1:39 IDENT xxx.pw


Makefile:8: recipe for target 'apply' failed
make: *** [apply] Error 1
```

**Comment by DavidWittman** [comment]
Oh, that's unfortunate... I believe that's happening because `domains` is a list variable and you're passing a string.

Try running this instead:

```
terraform apply -var 'domains=["xxx.pw"]' terraform/
```

**Comment by Fffrank** [comment]
How should I be inputting a list instead of a string?

**Comment by DavidWittman** [comment]
You could also enter `["xxx.pw"]` when prompted.

**Comment by DavidWittman** [comment]
@Fffrank I'm going to close this issue for now -- please feel free to respond if you're still having issues.

**Comment by Fffrank** [comment]
Thank you.  Haven't had time to mess with it but your advice did fix my original issue.  I'm now having trouble with terraform not finding my AWS credentials correctly but obviously that's not an issue with your code.

**Comment by DavidWittman** [comment]
Awesome. I have a hosted version you can use but I don't share it on Github. Send me an email (see my Github profile) and I'll give you the details.
