### ISSUE TITLE
New style reservation email doesn't always say "Your reservation is confirmed"

### ISSUE THREAD

**Issue by ScottBishop** [DavidWittman/serverless-southwest-check-in#48]
The string is hardcoded to look for `Your reservation is confirmed`, but when a reservation is changed, the subject line looks like this:

`John Doe's 10/26 San Francisco (XXXXXX): Your change is confirmed.`

We might need to change this to a regex to exclude the second word from the check.

**Comment by DavidWittman** [comment]
Thanks Scott. I also noticed that some of the emails don't even say "Your
reservation is confirmed"... I'll probably need to improve that code path
to check a few different regexes.
