### ISSUE TITLE
Schedule check in getting 404 resulting in ReservationCancelledError

### ISSUE THREAD

**Issue by ScottBishop** [DavidWittman/serverless-southwest-check-in#50]
Haven't had time to look into this yet but just wanted to make sure you are aware in case the API changed or they blocked access. 

```
16:34:32
START RequestId: dd3eb32c-5ef7-4abb-8c6f-348bd29e3739 Version: $LATEST
16:34:32
[INFO]	2018-10-29T16:34:32.18Z	dd3eb32c-5ef7-4abb-8c6f-348bd29e3739	Looking up reservation XXXXXX for John Doe
16:34:32
./vendor/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
16:34:32
InsecureRequestWarning)
16:34:33
: ReservationCancelledError Traceback (most recent call last): File "/var/task/handler.py", line 66, in schedule_check_in first_name, last_name, confirmation_number File "/var/task/lib/swa.py", line 43, in from_passenger_info method="get" File "/var/task/lib/swa.py", line 134, in _make_request raise exceptions.ReservationCancelledError() lib.exceptions.ReservationCancelledError
: ReservationCancelledError
Traceback (most recent call last):
File "/var/task/handler.py", line 66, in schedule_check_in
first_name, last_name, confirmation_number
File "/var/task/lib/swa.py", line 43, in from_passenger_info
method="get"
File "/var/task/lib/swa.py", line 134, in _make_request
raise exceptions.ReservationCancelledError()
lib.exceptions.ReservationCancelledError
16:34:33
END RequestId: dd3eb32c-5ef7-4abb-8c6f-348bd29e3739
16:34:33
REPORT RequestId: dd3eb32c-5ef7-4abb-8c6f-348bd29e3739	Duration: 1507.22 ms	Billed Duration: 1600 ms Memory Size: 128 MB	Max Memory Used: 37 MB
```

Its hitting this block in `swa.py`

```
if response.status_code == 404:
        raise exceptions.ReservationCancelledError()
```

**Comment by DavidWittman** [comment]
@ScottBishop thanks for reporting this. It doesn't look like their API changed -- I just tested a reservation and it seems to be working okay in my case.

Are you sure this reservation exists?

**Comment by ScottBishop** [comment]
I am positive the reservation exists, just bought them this morning. I tried it with 2 different reservations. 

One has a middle initial: `John A Doe's 12/01 San Francisco trip...`
And the other has a full middle name: `John Andy Doe's 12/01 San Francisco trip...`

Both seeing the same error, could be related?

**Comment by DavidWittman** [comment]
FWIW You'll need to be running at least https://github.com/DavidWittman/serverless-southwest-check-in/commit/d27d5d166551c0cb468edef205b46efe680746ce for the above functionality to work.

**Comment by ScottBishop** [comment]
"Manual mode" worked. If I get some time I'll submit my first PR for this :)

**Comment by DavidWittman** [comment]
Please do! I'll warn you that it's a bit of a difficult problem to solve because all of the different names and formats they seem to use for these emails. But you can add them to the test suite at https://github.com/DavidWittman/serverless-southwest-check-in/blob/master/lambda/tests/test_email.py#L102-L104 and just run `make test` and get some feedback as to whether or not things are working.

Just to add to the pile, I just booked a flight and got the following email format:

```
David L Jr Wittman's 11/23 San Francisco trip (ABC123): Your reservation is confirmed.
```

**Comment by DavidWittman** [comment]
The parser issues have been fixed, but this exception is still unclear here. This is more of a ReservationNotFound error, not a ReservationCancelled error.
