### ISSUE TITLE
SouthwestApiErrors - 503 error on check in, 400 error on schedule check in

### ISSUE THREAD

**Issue by ScottBishop** [DavidWittman/serverless-southwest-check-in#69]
I'm recently receiving errors for both scheduling a check in and on check in. 2 different errors. Might be related, but haven't confirmed yet

Check In
```
status_code=503 msg="Requested resource is currently not available.": SouthwestAPIError
Traceback (most recent call last):
  File "/var/task/handlers/check_in.py", line 34, in main
    resp = swa.check_in(passengers, confirmation_number)
  File "/var/task/swa.py", line 152, in check_in
    content_type
  File "/var/task/swa.py", line 137, in _make_request
    response.status_code, msg))
exceptions.SouthwestAPIError: status_code=503 msg="Requested resource is currently not available."
```

Schedule Check In
```
status_code=400 msg="": SouthwestAPIError
Traceback (most recent call last):
  File "/var/task/handlers/schedule_check_in.py", line 54, in main
    first_name, last_name, confirmation_number
  File "/var/task/swa.py", line 43, in from_passenger_info
    method="get"
  File "/var/task/swa.py", line 137, in _make_request
    response.status_code, msg))
exceptions.SouthwestAPIError: status_code=400 msg=""
```

**Comment by DavidWittman** [comment]
I have the new API key, but they've made some changes to their API which
are going to require some modifications here. I'm looking into it,
hopefully I can get to the bottom of it soon.

**Comment by DavidWittman** [comment]
@ScottBishop This should be fixed now. All the tests are broken right now, and it will no longer email the boarding passes, but at least it checks in.

**Comment by ScottBishop** [comment]
Thanks for the quick turn around David, really appreciate it. I was out of town so didn't get a chance to look at it. Looks like they changed their API quite a bit.

**Comment by DavidWittman** [comment]
No problem... I'm not 100% sure it works for multi-passenger check-ins, so if you happen to get any info on that please let me know.
