### ISSUE TITLE
Add notes on monthly cost of running the service

### ISSUE THREAD

**Issue by DavidWittman** [DavidWittman/serverless-southwest-check-in#8]

**Comment by DavidWittman** [comment]
Lambda:

> First 1 million requests per month are free

**Comment by DavidWittman** [comment]
https://aws.amazon.com/lambda/pricing/

**Comment by dwertheimer** [comment]
I would suggest that you tell people how much it will cost to run for a month, but you also add in the instructions how to turn off the trigger when they don't have any upcoming flights. It's pretty simple -- 2 clicks to disable and then to re-enable when they upload new flights.

[https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/southwest-checkin-dev-check_in?tab=triggers](url)

**Comment by DavidWittman** [comment]
It's cheap, like < $2/mo. Just closing this.
