### ISSUE TITLE
403 Error on sw-check-in

### ISSUE THREAD

**Issue by ScottBishop** [DavidWittman/serverless-southwest-check-in#80]
Recently getting 403 error on check in. It was working last week.

```
[INFO] 2020-06-18T21:55:03.315Z 14901214-2e73-4aa3-9328-8dab72e14e81 Checking in John Doe (ABC123)

  | 2020-06-18T14:55:03.628-07:00 | [ERROR] 2020-06-18T21:55:03.628Z 14901214-2e73-4aa3-9328-8dab72e14e81 Error checking in: status_code=403 msg="Forbidden"
  | 2020-06-18T14:55:03.629-07:00 | status_code=403 msg="Forbidden": SouthwestAPIErrorTraceback (most recent call last):  File "/var/task/handlers/check_in.py", line 36, in main    resp = swa.check_in(first_name, last_name, confirmation_number)  File "/var/task/swa.py", line 126, in check_in    session = _make_request("get", page + "/" + confirmation_number, params)  File "/var/task/swa.py", line 48, in _make_request    response.status_code, msg))exceptions.SouthwestAPIError: status_code=403 msg="Forbidden"

**Comment by DavidWittman** [comment]
Weird... I had a check-in work today at 1:15pm CT. So roughly 4 hours before yours failed. Are you running from master?

edit: Also was it an international flight (are those even a thing now?) and/or companion pass?

**Comment by ScottBishop** [comment]
Weird. I am up-to-date with master and it was a domestic one way flight. 403 -- so maybe the API Key is no longer valid? 

I have another check in at 7:30am tomorrow so will have another data point. I'll keep you posted.

**Comment by ScottBishop** [comment]
And .... it worked. I don't have a good explanation that would explain a 403, but go figure.

Closing this and we can reopen if needed.

**Comment by DavidWittman** [comment]
Thanks for the follow up... Is there any chance it ran at the wrong time
somehow?

**Comment by ScottBishop** [comment]
It ran at the correct time, however, I have my deployment set to check in 3 seconds after check in time instead of 7 seconds. I've never had an issue with it but it is probably not related as the retry requests failed with the same forbidden error too.
