### ISSUE TITLE
403 on schedule check in lambda

### ISSUE THREAD

**Issue by ScottBishop** [DavidWittman/serverless-southwest-check-in#82]
Was working this weekend, issue first seen today.

```
[INFO] 2021-07-19T16:37:46.147Z 3c5efbd4-8b76-4087-a03d-dd83c93cdc2a Looking up reservation ABC123 for John Doe
  | 2021-07-19T09:37:46.289-07:00 | status_code=403 msg="Forbidden": SouthwestAPIError Traceback (most recent call last): File "/var/task/handlers/schedule_check_in.py", line 35, in main first_name, last_name, confirmation_number File "/var/task/swa.py", line 73, in from_passenger_info params File "/var/task/swa.py", line 48, in _make_request response.status_code, msg)) exceptions.SouthwestAPIError: status_code=403 msg="Forbidden"
  | 2021-07-19T09:37:46.309-07:00 | END RequestId: 3c5efbd4-8b76-4087-a03d-dd83c93cdc2a
```

**Comment by DavidWittman** [comment]
Yeah, I've seen this occasionally. Most check-ins are working but it seems
like some require information regarding COVID vaccinations when checking in
and they fail in this way. Just my best guess.

**Comment by ScottBishop** [comment]
This was for a new booking, the email is parsed correctly but seeing this error when scheduling the check in. At this point I wouldn't think any COVID information would be required to look up a reservation.

**Comment by DavidWittman** [comment]
Ohh sorry I misread this and thought it was on check-in. Are any check-ins
scheduling successfully for you?
